<a href="https://colab.research.google.com/github/Peotr-B/Scikit-Learn-Python1/blob/main/Scikit_Learn_Python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
print('Hello, Peotr!')

Hello, Peotr!


Изучение и применение программного пакета Scikit-Learn Python для машинного обучения

https://russianblogs.com/article/92821254172/

In [56]:
from sklearn import datasets

In [57]:
#iris = datasets.load_iris()

Импорт набора данных Iris
         возвращаемое значение:
         X-первые 5 данных обучающих функций
         y-первые 5 категорий обучающих данных
         X_shape - размер двумерного массива данных функции обучения

In [58]:
#initialization

In [59]:
X = []
y = []
X_shape = () 
    
# Пожалуйста, добавьте сюда код реализации

In [60]:
#********** Begin *********

In [61]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
X_shape = X.shape
#X = X[:5]
XX = X[:5]  #Двойное "X" - чтобы не ограничивать исходный массив, в дальнейшем 
#нужно будет менять пределы, а если использовать только одинарый X, то менять
#можно будет только внутри вырезанного массива
yy = y[:5]

In [62]:
XX

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [63]:
yy

array([0, 0, 0, 0, 0])

In [64]:
X_shape

(150, 4)

In [65]:
XX.mean(), XX.std()

(2.435, 1.7855741373575056)

In [66]:
XX.mean(axis=0), XX.std(axis=0)

(array([4.86, 3.28, 1.4 , 0.2 ]),
 array([0.18547237, 0.23151674, 0.06324555, 0.        ]))

In [67]:
from sklearn import preprocessing
import numpy as np

In [68]:
XX_scaled = preprocessing.scale(XX)

In [69]:
XX_scaled

array([[ 1.29399328,  0.95025527,  0.        ,  0.        ],
       [ 0.21566555, -1.2094158 ,  0.        ,  0.        ],
       [-0.86266219, -0.34554737, -1.58113883,  0.        ],
       [-1.40182605, -0.77748158,  1.58113883,  0.        ],
       [ 0.75482941,  1.38218948,  0.        ,  0.        ]])

In [70]:
XX_scaled.mean(), XX_scaled.std()

(1.1990408665951691e-15, 0.8660254037844386)

Обработка поперечных данных (строки):


In [71]:
XX_scaled.mean(axis=0), XX_scaled.std(axis=0)

(array([2.86437540e-15, 1.19904087e-15, 7.10542736e-16, 0.00000000e+00]),
 array([1., 1., 1., 0.]))

Обработка продольного направления (столбца):

In [72]:
XX_scaled.mean(axis=1), XX_scaled.std(axis=1)

(array([ 0.56106214, -0.24843756, -0.6973371 , -0.1495422 ,  0.53425472]),
 array([0.57407334, 0.56176359, 0.59549831, 1.11581163, 0.5784684 ]))

https://russianblogs.com/article/17772510890/

In [73]:
XX_train = XX

In [74]:
scaler = preprocessing.StandardScaler().fit(XX_train)

In [75]:
scaler

StandardScaler()

In [76]:
scaler.mean_

array([4.86, 3.28, 1.4 , 0.2 ])

In [77]:
scaler.scale_

array([0.18547237, 0.23151674, 0.06324555, 1.        ])

In [78]:
scaler.transform(XX_train)

array([[ 1.29399328,  0.95025527,  0.        ,  0.        ],
       [ 0.21566555, -1.2094158 ,  0.        ,  0.        ],
       [-0.86266219, -0.34554737, -1.58113883,  0.        ],
       [-1.40182605, -0.77748158,  1.58113883,  0.        ],
       [ 0.75482941,  1.38218948,  0.        ,  0.        ]])

In [79]:
XX_scaled.mean(), XX_scaled.std()

(1.1990408665951691e-15, 0.8660254037844386)

In [80]:
scaler.mean_

array([4.86, 3.28, 1.4 , 0.2 ])

In [81]:
XX_scaled.mean(axis=0), XX_scaled.std()

(array([2.86437540e-15, 1.19904087e-15, 7.10542736e-16, 0.00000000e+00]),
 0.8660254037844386)

In [82]:
min_max_scaler = preprocessing.MinMaxScaler()

In [83]:
XX_train_minmax = min_max_scaler.fit_transform(XX_train)

In [84]:
XX_train_minmax

array([[1.        , 0.83333333, 0.5       , 0.        ],
       [0.6       , 0.        , 0.5       , 0.        ],
       [0.2       , 0.33333333, 0.        , 0.        ],
       [0.        , 0.16666667, 1.        , 0.        ],
       [0.8       , 1.        , 0.5       , 0.        ]])

In [85]:
XX_test = np.array([[-8., 5., 2., -0.5]])

In [86]:
XX_test_minmax = min_max_scaler.transform(XX_test)

In [87]:
XX_test_minmax

array([[-25.2       ,   3.33333333,   3.5       ,  -0.7       ]])

In [88]:
X2_test = XX_test_minmax

In [89]:
X2_test

array([[-25.2       ,   3.33333333,   3.5       ,  -0.7       ]])

In [90]:
XXX = X[4:8]

In [91]:
XXX

array([[5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2]])

In [92]:
XXX_train = XXX

In [93]:
scaler3X = preprocessing.StandardScaler().fit(XXX_train)

In [94]:
scaler3X

StandardScaler()

In [95]:
scaler3X.mean_

array([5.   , 3.575, 1.5  , 0.275])

In [96]:
scaler.scale_

array([0.18547237, 0.23151674, 0.06324555, 1.        ])

In [97]:
XXX_scaled = preprocessing.scale(XXX)

In [98]:
XXX_scaled.mean(), XXX_scaled.std()

(-3.885780586188048e-16, 1.0)

In [99]:
XXX_train_minmax = min_max_scaler.fit_transform(XXX_train)

In [100]:
XXX_train_minmax

array([[0.5       , 0.4       , 0.        , 0.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [0.        , 0.        , 0.        , 0.5       ],
       [0.5       , 0.        , 0.33333333, 0.        ]])

In [101]:
XX_test_minmax = min_max_scaler.transform(XX_test)

In [102]:
XX_test_minmax

array([[-15.75,   3.2 ,   2.  ,  -3.5 ]])

In [103]:
X3_test = XX_test_minmax

In [104]:
X3_test

array([[-15.75,   3.2 ,   2.  ,  -3.5 ]])

In [106]:
X2_test

array([[-25.2       ,   3.33333333,   3.5       ,  -0.7       ]])